steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vital-bites-api', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vital-bites-api']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'vital-bites-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/vital-bites-api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DB_USER=vital_bites_user,DB_PASS=${_DB_PASS},DB_NAME=vital_bites,DB_HOST=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME},SECRET_KEY=${_SECRET_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY}'
    - '--add-cloudsql-instances'
    - '${_CLOUD_SQL_CONNECTION_NAME}'

substitutions:
  _DB_PASS: 'YOUR_USER_PASSWORD'
  _CLOUD_SQL_CONNECTION_NAME: 'YOUR_CONNECTION_NAME'
  _SECRET_KEY: 'your-secret-key'
  _OPENAI_API_KEY: 'your-openai-key'

images:
  - 'gcr.io/$PROJECT_ID/vital-bites-api'